namespace WTNS.Telemetry;

public struct OsInfo
{
    public List<string?>? BootDevice;
    public List<string?>? BuildNumber;
    public List<string?>? BuildType;
    public List<string?>? Caption;
    public List<string?>? CodeSet;
    public List<string?>? CountryCode;
    public List<string?>? CreationClassName;
    public List<string?>? CSCreationClassName;
    public List<string?>? CSDVersion;
    public List<string?>? CSName;
    public List<short>? CurrentTimeZone;
    public List<bool>? DataExecutionPrevention_Available;
    public List<bool>? DataExecutionPrevention_32BitApplications;
    public List<bool>? DataExecutionPrevention_Drivers;
    public List<byte>? DataExecutionPrevention_SupportPolicy;
    public List<bool>? Debug;
    public List<string?>? Description;
    public List<bool>? Distributed;
    public List<uint>? EncryptionLevel;

    // ForegroundApplicationBoost contains default value, from docs:
    // uint8 ForegroundApplicationBoost = 2;
    public List<byte>? ForegroundApplicationBoost;
    public List<ulong>? FreePhysicalMemory;
    public List<ulong>? FreeSpaceInPagingFiles;
    public List<ulong>? FreeVirtualMemory;
    public List<DateTime>? InstallDate;
    public List<uint>? LargeSystemCache;
    public List<DateTime>? LastBootUpTime;
    public List<DateTime>? LocalDateTime;
    public List<string?>? Locale;
    public List<string?>? Manufacturer;
    public List<uint>? MaxNumberOfProcesses;
    public List<ulong>? MaxProcessMemorySize;
    public List<string[]?>? MUILanguages;
    public List<string?>? Name;
    public List<uint>? NumberOfLicensedUsers;
    public List<uint>? NumberOfProcesses;
    public List<uint>? NumberOfUsers;
    public List<uint>? OperatingSystemSKU;
    public List<string?>? Organization;
    public List<string?>? OSArchitecture;
    public List<uint>? OSLanguage;
    public List<uint>? OSProductSuite;
    public List<ushort>? OSType;
    public List<string?>? OtherTypeDescription;
    public List<bool>? PAEEnabled;
    public List<string?>? PlusProductID;
    public List<string?>? PlusVersionNumber;
    public List<bool>? PortableOperatingSystem;
    public List<bool>? Primary;
    public List<uint>? ProductType;
    public List<string?>? RegisteredUser;
    public List<string?>? SerialNumber;
    public List<ushort>? ServicePackMajorVersion;
    public List<ushort>? ServicePackMinorVersion;
    public List<ulong>? SizeStoredInPagingFiles;
    public List<string?>? Status;
    public List<uint>? SuiteMask;
    public List<string?>? SystemDevice;
    public List<string?>? SystemDirectory;
    public List<string?>? SystemDrive;
    public List<ulong>? TotalSwapSpaceSize;
    public List<ulong>? TotalVirtualMemorySize;
    public List<ulong>? TotalVisibleMemorySize;
    public List<string?>? Version;
    public List<string?>? WindowsDirectory;
    public List<byte>? QuantumLength;
    public List<byte>? QuantumType;
}
